### ISSUE TITLE
MaterialYou Shell theme does not properly colour shell buttons

### ISSUE THREAD

**Issue by matguidi** [avanishsubbiah/material-you-theme#61] opened 2022-09-30 07:45 UTC
Hi, I've installed the extension and I really like it, congratulations for your work!
I've noticed a small inconsistency in how MaterialYou builds the theme for the GNOME shell. Although my MaterialYou theme is based on green (as you can see from the colouring of the number in the calendar), the shell buttons remain in the original Adwaita blue, no matter whether I try to generate themes in different colours. Those buttons are never modified? Any ideas?

![Schermata del 2022-09-30 09-35-23_2](https://user-images.githubusercontent.com/59918868/193218529-dbc429c4-60a9-4439-82c5-34f7adfa562e.png)

**Comment by ardjuh** [comment] 2022-10-03 15:24
Duplicate of #41

**Closed** 2022-10-14 18:42 UTC
