### ISSUE TITLE
Argument filename may not be null

### ISSUE THREAD

**Issue by aniketfuryrocks** [avanishsubbiah/material-you-theme#22] opened 2022-08-04 20:56 UTC
```bash
 8% ❯ freshfetch

  
            /:-------------:\\         aniket@
         :-------------------::
       :-----------/shhOHbmp---:\\     OS: Fedora Linux 36 (Workstation Edition) x86_64
     /-----------omMMMNNNMMD  ---:     Host: 81BF
    :-----------sMMMMNMNMP.    ---:    Kernel: Linux 5.18.13-200.fc36.x86_64
   :-----------:MMMdP-------    ---\\  Uptime: 10 minutes
  ,------------:MMMd--------    ---:   Packages: 1740 (rpm), 23 (flatpak)
  :------------:MMMd-------    .---:   Shell: fish 
  :----    oNMMMMMMMMMNho     .----:   Resolution: 1920x1080
  :--     .+shhhMMMmhhy++   .------/   DE: GNOME GNOME Shell 42.3.1
  :-    -------:MMMd--------------:    WM: gnome-shell
  :-   --------/MMMd-------------;     CPU: Intel Core i5-8250U  @ 1.60GHz (8) @ 3.4GHz
  :-    ------/hMMMy------------:      Board: LENOVO INVALID
  :-- :dMNdhhdNMMNo------------;       Memory: 1648MB / 7813MB
  :---:sdNMMMMNds:------------:
  :------:://:-------------::                                  
  :---------------------://                                    
```
![image](https://user-images.githubusercontent.com/42654595/182951098-d84c7128-f6a4-4363-bcec-18df6fce0520.png)

**Comment by bentuhana** [comment] 2022-08-04 21:49
Duplicate of #14

**Closed** 2022-08-07 03:53 UTC
